import { ChatSession } from '@/types/chat';

export function exportChatToText(session: ChatSession) {
    if (!session) return;

    const date = new Date(session.timestamp).toLocaleDateString();
    const time = new Date(session.timestamp).toLocaleTimeString();
    const filename = `HFP-Record-${new Date().toISOString().split('T')[0]}.txt`;

    let content = `HEALTH FIRST PRIORITY - SECURE CONFIDENTIAL RECORD\n`;
    content += `=================================================\n`;
    content += `Session ID: ${session.id}\n`;
    content += `Date: ${date} ${time}\n`;
    content += `Topic: ${session.title}\n`;
    content += `=================================================\n\n`;

    session.messages.forEach((msg, index) => {
        const role = msg.role === 'user' ? 'CLINICIAN/USER' : 'HFP SYSTEM';
        content += `[${role}]:\n${msg.content}\n\n`;
        content += `-------------------------------------------------\n\n`;
    });

    content += `\n*** END OF RECORD ***\n`;
    content += `Generated by HealthFirstPriority Secure Workspace`;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
}
